module Prpl
  module Config
    module Templates
      module Products
        module Serializers
          class ProductById
            @product: untyped

            # Initializes the serializer with a product hash.
            #
            # @param product [Hash] The structured product data returned from the GraphQL query.
            def initialize: (untyped product) -> void

            # Serializes the product data.
            #
            # @return [Hash] A hash with standardized product data.
            def serialize: () -> (::Hash[untyped, untyped] | { id: untyped, title: untyped, variants: untyped, collections: untyped })

            private

            # Serializes the variants array.
            #
            # @return [Array<Hash>] An array of serialized variants.
            def serialize_variants: () -> (::Array[untyped] | untyped)

            # Serializes the collections array.
            #
            # @return [Array<Hash>] An array of serialized collections.
            def serialize_collections: () -> (::Array[untyped] | untyped)
          end
        end
      end
    end
  end
end
