module Propel
  module Config
    module Templates
      module Products
        module Queries
          class GetProductVariantById
            @client: untyped

            GRAPHQL_QUERY: "query GetProductVariantById($variantId: ID!) {\n  productVariant(id: $variantId) {\n    id\n    title\n    sku\n    inventoryQuantity\n    price\n    compareAtPrice\n    selectedOptions {\n      name\n      value\n    }\n    product {\n      id\n      title\n    }\n    media(first: 10) {\n      edges {\n        node {\n          ... on MediaImage {\n            id\n            alt\n            image {\n              url\n            }\n          }\n          ... on Video {\n            id\n            alt\n            previewImage {\n              url\n            }\n          }\n        }\n      }\n    }\n  }\n}\n"

            attr_reader client: untyped

            # Initializes the GetProductVariantById query class with a GraphQL client.
            #
            # @param client [Object] A GraphQL client instance to execute queries.
            def initialize: (untyped client) -> void

            # Fetches a product variant by its Shopify GraphQL ID.
            #
            # @param variant_id [String] The Shopify GraphQL ID of the product variant.
            # @return [Hash, nil] The structured variant data or nil if not found.
            def fetch_variant: (untyped variant_id) -> untyped
          end
        end
      end
    end
  end
end
